db-mongo:
  image: mongo:latest
  container_name: cl-mongo
  networks:
    - photostack-network
  volumes:
    - ./db-notes-mongo:/data/db
    - ./mongod.conf:/etc/mongod.conf
  command: mongod --config /etc/mongod.conf

db-mongo-admin:
  image: mongo-express
  container_name: db-mongo-admin
  networks:
    - _network name_
  environment:
    ME_CONFIG_OPTIONS_EDITORTHEME: ambiance
    ME_CONFIG_BASICAUTH_USERNAME: user
    ME_CONFIG_BASICAUTH_PASSWORD: fairlylongpassword
    ME_CONFIG_MONGODB_SERVER: some-mongo
